# Generated by Django 2.1.7 on 2019-03-01 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published_date1',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
