# Generated by Django 2.1.7 on 2019-03-02 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190302_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post1',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post'),
        ),
    ]
