# Generated by Django 2.1.7 on 2019-03-02 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190302_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post1',
            new_name='post',
        ),
    ]
