# Generated by Django 2.1.7 on 2019-03-02 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_author2'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post1',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_comment', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post'),
        ),
    ]
