# Generated by Django 2.1.7 on 2019-03-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
