# Generated by Django 2.1.4 on 2019-03-06 03:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190306_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
