# Generated by Django 2.1.4 on 2019-03-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_votes_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
